spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  flyway:
    baseline-on-migrate: true

hsql:
  url: jdbc:hsqldb:hsql://hsqldb:9001/db1
  username: sa
  password:

server:
  port: 8081

runner:
  duration: 3600000

